
name: bias-correction installs

on: pull_request

jobs:

  install-bias-correction:  # Installs bias-correction on various OS.
    name: Install bias-correction, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          shell: bash {0}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python -c "import bias_correction"
